function regseateamopp = import_team_opp(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   REGSEATEAMOPP = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   REGSEATEAMOPP = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   regseateamopp = importfile('reg_sea_team_opp.csv', 2, 31);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/12/05 14:07:56

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
regseateamopp = table(dataArray{1:end-1}, 'VariableNames', {'TEAM_ID','TEAM_NAME','GP','W','L','W_PCT','MIN','OPP_FGM','OPP_FGA','OPP_FG_PCT','OPP_FG3M','OPP_FG3A','OPP_FG3_PCT','OPP_FTM','OPP_FTA','OPP_FT_PCT','OPP_OREB','OPP_DREB','OPP_REB','OPP_AST','OPP_TOV','OPP_STL','OPP_BLK','OPP_BLKA','OPP_PF','OPP_PFD','OPP_PTS','PLUS_MINUS','CFID','CFPARAMS'});

