function vars = import_vars(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   VARS = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   VARS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   vars = importfile('vars.csv', 2, 31);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/12/04 13:17:28

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8,9,10,11,12]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8,9,10,11,12]);
rawCellColumns = raw(:, [1,13,14,15,16]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
vars = table;
vars.teams_playing = rawCellColumns(:, 1);
vars.num_teams_playing = cell2mat(rawNumericColumns(:, 1));
vars.salary_cap = cell2mat(rawNumericColumns(:, 2));
vars.average_per_player = cell2mat(rawNumericColumns(:, 3));
vars.three_point_shot = cell2mat(rawNumericColumns(:, 4));
vars.two_point_shot = cell2mat(rawNumericColumns(:, 5));
vars.free_throw = cell2mat(rawNumericColumns(:, 6));
vars.rebounds = cell2mat(rawNumericColumns(:, 7));
vars.assists = cell2mat(rawNumericColumns(:, 8));
vars.blocked_shots = cell2mat(rawNumericColumns(:, 9));
vars.steals = cell2mat(rawNumericColumns(:, 10));
vars.turnovers = cell2mat(rawNumericColumns(:, 11));
vars.position = rawCellColumns(:, 2);
vars.team = rawCellColumns(:, 3);
vars.injury_indicator = rawCellColumns(:, 4);
vars.injury_details = rawCellColumns(:, 5);

